# Generated by Django 3.1 on 2021-07-02 06:16

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210630_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portproductgallery',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='products/port/'),
        ),
        migrations.AlterField(
            model_name='portproductgallery',
            name='video',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='products/port/'),
        ),
    ]
