# Generated by Django 3.1 on 2021-07-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210702_0616'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_time_option',
            field=models.CharField(blank=True, choices=[('ready to ship', 'Ready To Ship'), ('needs time to ship', 'Needs Time To Ship')], max_length=32, null=True),
        ),
    ]
