# Generated by Django 3.1 on 2021-07-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_delivery_time_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='portdeals',
            name='lat',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='portdeals',
            name='lng',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
