# Generated by Django 3.1 on 2021-07-12 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210709_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portdeals',
            name='lat',
            field=models.FloatField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='portdeals',
            name='lng',
            field=models.FloatField(blank=True, max_length=250, null=True),
        ),
    ]
