# Generated by Django 3.1 on 2021-07-12 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210617_0618'),
        ('product', '0008_auto_20210712_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portdeals',
            name='location',
        ),
        migrations.AddField(
            model_name='portdeals',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address'),
        ),
    ]
