# Generated by Django 3.1 on 2021-07-17 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_productimage_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
