# Generated by Django 3.1 on 2021-07-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_auto_20210717_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='portdeals',
            name='container_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
