# Generated by Django 3.1 on 2021-07-20 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_portdeals_container_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portdeals',
            name='container_number',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
