# Generated by Django 3.1 on 2021-07-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_auto_20210720_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='portdeals',
            name='is_expire',
            field=models.BooleanField(default=False),
        ),
    ]
