# Generated by Django 3.1 on 2021-08-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_certificatetype_image'),
        ('product', '0017_auto_20210722_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='certificate',
            field=models.ManyToManyField(blank=True, related_name='_product_certificate_+', to='profile.Certificate'),
        ),
    ]
