# Generated by Django 3.1 on 2021-08-05 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_product_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='certificate',
        ),
    ]
