# Generated by Django 3.1 on 2021-08-07 10:44

from django.db import migrations, models
import koytola.core.db.fields
import koytola.core.utils.editorjs


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_remove_product_certificate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenExchange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=5)),
                ('timestamp', models.DateTimeField()),
                ('rates', koytola.core.db.fields.SanitizedJSONField(blank=True, default=dict, sanitizer=koytola.core.utils.editorjs.clean_editor_js)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
