# Generated by Django 3.1 on 2021-08-13 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_openexchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquery',
            name='user',
        ),
        migrations.AddField(
            model_name='productquery',
            name='email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='productquery',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
