# Generated by Django 3.1 on 2021-08-31 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20210813_1140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productquery',
            name='email',
        ),
    ]
