# Generated by Django 3.1 on 2021-09-07 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_remove_contact_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0023_auto_20210906_0701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productquery',
            old_name='is_closed',
            new_name='is_buyer_closed',
        ),
        migrations.RemoveField(
            model_name='productquery',
            name='seller',
        ),
        migrations.RemoveField(
            model_name='productquery',
            name='user',
        ),
        migrations.AddField(
            model_name='productquery',
            name='is_seller_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ProductQueryUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_query', to='profile.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_query', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productquery',
            name='product_query_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_query_user', to='product.productqueryusers'),
        ),
    ]
