# Generated by Django 3.1 on 2021-09-17 06:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import koytola.product.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0024_auto_20210907_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='productqueryusers',
            name='room_id',
            field=models.CharField(default=django.utils.crypto.get_random_string, max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='QueryChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, max_length=65500, null=True)),
                ('file_message', models.FileField(blank=True, null=True, upload_to=koytola.product.models.QueryChat.file_message_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_by_user', to=settings.AUTH_USER_MODEL)),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_to_user', to='product.productqueryusers')),
                ('to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_to_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
