# Generated by Django 3.1 on 2021-06-17 06:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('account', '0002_auto_20210617_0618'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=128)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('subject', models.CharField(default='', max_length=128)),
                ('content', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('new', 'New sent message'), ('ongoing', 'Ongoing message status'), ('completed', 'Message status is completed'), ('spam', 'Message status is spam'), ('other', 'Message status is other')], default='new', max_length=255)),
                ('note', models.TextField(blank=True, default='', null=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'permissions': [('manage_contact_messages', 'Manage contact messages.')],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, default='', max_length=255, null=True, upload_to='images/', verbose_name='Image')),
                ('alt_text', models.CharField(default='', max_length=256, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(default='', max_length=256, null=True)),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'ordering': ['-creation_date'],
                'permissions': [('manage_site_images', 'Manage site images.')],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('default_mail_sender_name', models.CharField(blank=True, default='', max_length=78, validators=[django.core.validators.RegexValidator('[\\n\\r]', code='forbidden_character', inverse_match=True, message='New lines are not allowed.'), django.core.validators.MaxLengthValidator(78)])),
                ('default_mail_sender_address', models.EmailField(blank=True, max_length=254, null=True)),
                ('account_set_password_url', models.CharField(blank=True, max_length=255, null=True)),
                ('bottom_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.menu')),
                ('company_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.address')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.site')),
                ('top_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='menu.menu')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'permissions': (('manage_settings', 'Manage settings.'), ('manage_translations', 'Manage translations.')),
            },
        ),
        migrations.CreateModel(
            name='SiteSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=128)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Subscriber',
                'verbose_name_plural': 'Site Subscribers',
                'permissions': [('manage_site_subscribers', 'Manage site subscribers.')],
            },
        ),
        migrations.CreateModel(
            name='SiteSettingsTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('header_text', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='site.sitesettings')),
            ],
            options={
                'verbose_name': 'Site Settings Translation',
                'verbose_name_plural': 'Site Settings Translations',
                'unique_together': {('language_code', 'site_settings')},
            },
        ),
        migrations.CreateModel(
            name='AuthorizationKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('facebook', 'Facebook-Oauth2'), ('google-oauth2', 'Google-Oauth2')], max_length=20)),
                ('key', models.TextField()),
                ('password', models.TextField()),
                ('site_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site.sitesettings')),
            ],
            options={
                'verbose_name': 'Authorization Key',
                'verbose_name_plural': 'Authorization Keys',
                'unique_together': {('site_settings', 'name')},
            },
        ),
    ]
