# Generated by Django 3.1 on 2021-06-17 06:18

from django.db import migrations, models
import koytola.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PluginConfiguration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=128, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('configuration', models.JSONField(blank=True, default=dict, encoder=koytola.core.utils.json_serializer.CustomJsonEncoder, null=True)),
            ],
            options={
                'permissions': (('manage_plugins', 'Manage plugins'),),
            },
        ),
    ]
