# Generated by Django 3.1 on 2021-06-17 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import koytola.core.utils.json_serializer


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=koytola.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=koytola.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('status', models.CharField(choices=[('cancelled', 'The order was cancelled'), ('completed', 'The order was completed'), ('created', 'The order was created'), ('fulfilled', 'The order was fulfilled'), ('paid', 'The order was paid'), ('pending', 'The order was pending'), ('marked_as_paid', 'The order was manually marked as fully paid'), ('email_sent', 'The email was sent'), ('payment_authorized', 'The payment was authorized'), ('payment_captured', 'The payment was captured'), ('payment_refunded', 'The payment was refunded'), ('payment_voided', 'The payment was voided'), ('payment_failed', 'The payment was failed'), ('external_service_notification', 'Notification from external service'), ('invoice_requested', 'An invoice was requested'), ('invoice_generated', 'An invoice was generated'), ('invoice_updated', 'An invoice was updated'), ('invoice_sent', 'An invoice was sent'), ('note_added', 'A note was added to the order'), ('other', 'An unknown order event containing a message')], default='created', max_length=32)),
                ('language_code', models.CharField(default='en', max_length=35)),
                ('user_email', models.EmailField(blank=True, default='', max_length=254)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('token', models.CharField(blank=True, max_length=36, unique=True)),
                ('total_net_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_gross_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('note', models.TextField(blank=True, default='')),
                ('billing_address', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='account.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
                'permissions': (('manage_orders', 'Manage orders.'),),
            },
        ),
        migrations.CreateModel(
            name='OrderEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(choices=[('CANCELLED', 'cancelled'), ('COMPLETED', 'completed'), ('CREATED', 'created'), ('FULFILLED', 'fulfilled'), ('PAID', 'paid'), ('PENDING', 'pending'), ('MARKED_AS_PAID', 'marked_as_paid'), ('EMAIL_SENT', 'email_sent'), ('PAYMENT_AUTHORIZED', 'payment_authorized'), ('PAYMENT_CAPTURED', 'payment_captured'), ('PAYMENT_REFUNDED', 'payment_refunded'), ('PAYMENT_VOIDED', 'payment_voided'), ('PAYMENT_FAILED', 'payment_failed'), ('EXTERNAL_SERVICE_NOTIFICATION', 'external_service_notification'), ('INVOICE_REQUESTED', 'invoice_requested'), ('INVOICE_GENERATED', 'invoice_generated'), ('INVOICE_UPDATED', 'invoice_updated'), ('INVOICE_SENT', 'invoice_sent'), ('NOTE_ADDED', 'note_added'), ('OTHER', 'other')], max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=koytola.core.utils.json_serializer.CustomJsonEncoder)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='order.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
