# Generated by Django 3.1 on 2021-06-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roetter',
            name='category',
            field=models.TextField(blank=True, max_length=65500, null=True),
        ),
    ]
