# Generated by Django 3.1 on 2021-07-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_roetter_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='brochure',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='index',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
