# Generated by Django 3.1 on 2021-09-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20210902_1202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='company',
        ),
    ]
