# Generated by Django 3.1 on 2021-06-17 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('Support', 'Support'), ('Feedback', 'Feedback'), ('Recommendation', 'Recommendation'), ('New Feature Request', 'New Feature Request'), ('Other', 'Other')], default='Support')),
                ('subject', models.CharField(default='', max_length=128)),
                ('content', models.TextField(max_length=600)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, default='', max_length=256)),
                ('status', models.TextField(choices=[('New', 'New'), ('On Progress', 'On Progress'), ('Completed', 'Completed'), ('Other', 'Other')], default='New')),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Helpdesk Ticket',
                'verbose_name_plural': 'Helpdesk Tickets',
                'ordering': ['-creation_date'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=600)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='helpdesk.ticket')),
            ],
            options={
                'verbose_name': 'Ticket Message',
                'verbose_name_plural': 'Ticket Messages',
                'ordering': ['-creation_date'],
            },
        ),
    ]
