# Generated by Django 3.1 on 2021-06-17 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.crypto
import django.utils.timezone
import django_countries.fields
import koytola.account.models
import koytola.core.utils.json_serializer
import phonenumber_field.modelfields
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('private_metadata', models.JSONField(blank=True, default=dict, encoder=koytola.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=koytola.core.utils.json_serializer.CustomJsonEncoder, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_id', models.CharField(default=django.utils.crypto.get_random_string, max_length=12, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('phone', koytola.account.models.PossiblePhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('is_active', models.BooleanField(default=True)),
                ('is_seller', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('avatar', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='user-avatars')),
                ('jwt_token_key', models.CharField(default=django.utils.crypto.get_random_string, max_length=24)),
            ],
            options={
                'ordering': ('email',),
                'permissions': (('manage_users', 'Manage accounts.'), ('manage_staff', 'Manage staff.')),
            },
        ),
        migrations.CreateModel(
            name='AccountEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('type', models.CharField(choices=[('ACCOUNT_CREATED', 'account_created'), ('ACCOUNT_DELETED', 'account_deleted'), ('ACCOUNT_UPDATED', 'account_updated'), ('PASSWORD_RESET_LINK_SENT', 'password_reset_link_sent'), ('PASSWORD_RESET', 'password_reset'), ('EMAIL_CHANGED_REQUEST', 'email_changed_request'), ('PASSWORD_CHANGED', 'password_changed'), ('EMAIL_CHANGED', 'email_changed'), ('ACCOUNT_ACTIVATED_BY_STAFF', 'account_activated_by_staff'), ('ACCOUNT_DEACTIVATED_BY_STAFF', 'account_deactivated_by_staff'), ('ACCOUNT_CREATED_BY_STAFF', 'account_created_by_staff'), ('ACCOUNT_DELETED_BY_STAFF', 'account_deleted_by_staff'), ('EMAIL_ASSIGNED_BY_STAFF', 'email_assigned_by_staff'), ('EMAIL_UPDATED_BY_STAFF', 'email_updated_by_staff'), ('NAME_ASSIGNED_BY_STAFF', 'name_assigned_by_staff'), ('NOTE_ADDED_BY_STAFF', 'note_added_by_staff'), ('PLACED_ORDER', 'placed_order'), ('ORDER_UPDATE', 'order_update'), ('NOTE_ADDED_TO_ORDER', 'note_added_to_order'), ('DIGITAL_LINK_DOWNLOADED', 'digital_link_downloaded'), ('PROFILE_CREATED', 'profile_created'), ('PROFILE_UPDATED', 'profile_updated'), ('PROFILE_DELETED', 'profile_deleted'), ('PROFILE_CREATED_BY_STAFF', 'profile_created_by_staff'), ('PROFILE_UPDATED_BY_STAFF', 'profile_updated_by_staff'), ('PROFILE_DELETED_BY_STAFF', 'profile_deleted_by_staff'), ('PROFILE_ACTIVATED_BY_STAFF', 'profile_activated_by_staff'), ('PROFILE_DEACTIVATED_BY_STAFF', 'profile_deactivated_by_staff'), ('PRODUCT_CREATED', 'product_created'), ('PRODUCT_UPDATED', 'product_updated'), ('PRODUCT_DELETED', 'product_deleted'), ('PRODUCT_CREATED_BY_STAFF', 'product_created_by_staff'), ('PRODUCT_UPDATED_BY_STAFF', 'product_updated_by_staff'), ('PRODUCT_DELETED_BY_STAFF', 'product_deleted_by_staff'), ('PRODUCT_ACTIVATED_BY_STAFF', 'product_activated_by_staff'), ('PRODUCT_DEACTIVATED_BY_STAFF', 'product_deactivated_by_staff')], max_length=255)),
                ('parameters', models.JSONField(blank=True, default=dict, encoder=koytola.core.utils.json_serializer.CustomJsonEncoder)),
            ],
            options={
                'ordering': ['date'],
                'permissions': (('manage_account_events', 'Manage account events'),),
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(blank=True, default='', max_length=64)),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('company_name', models.CharField(blank=True, max_length=256)),
                ('street_address_1', models.CharField(blank=True, max_length=256, null=True)),
                ('street_address_2', models.CharField(blank=True, max_length=256, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('city_area', models.CharField(blank=True, max_length=128, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('country_area', models.CharField(blank=True, max_length=128, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
            ],
            options={
                'ordering': ['address_name', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('flag', models.FileField(blank=True, null=True, upload_to='Country-flag')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StaffNotificationRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='staff_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('staff_email',),
            },
        ),
    ]
