# Generated by Django 3.1 on 2021-08-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210831_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
    ]
