# Generated by Django 3.1 on 2021-09-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='linkedin_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
